### PR TITLE
Add Status Field; Historic Rates Response Interface

### PR DESCRIPTION
**Pull request by beckenrode**
Adding the status field for the returned Product list

### CODE REVIEW

**Comment by beckenrode** [comment]
Created a historic rates interface to be used instead of raw data

**Comment by benfranke** [comment]
Thank you for your submission and sorry this took so long, looks like I didn't setup my e-mail notifications appropriately.

**Comment by mattsims** [comment]
Looks like the Currency class also needs a status field – let me know if you need me to PR.

**Comment by benfranke** [comment]
Should be fixed in tag 0.0.2.

**Pull request merged**
